name: atelier
description: atelier app
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^0.5.6+1
  easy_localization: ^1.3.1
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.3+2
  firebase_messaging: ^6.0.9
  rxdart: ^0.23.1
  mime: ^0.9.6+3
  http: ^0.12.0+4
  pin_input_text_field: ^3.0.1
  draggable_scrollbar: ^0.0.4
  image_picker: ^0.6.3+1
  image_cropper: ^1.2.0
  bubble_animated_tabbar: ^1.0.2
  pull_to_refresh: ^1.5.8
  url_launcher: ^5.4.1
  flutter_rating_bar: ^3.0.1+1  
  sliding_sheet: ^0.2.5
  flutter_show_more: ^0.1.2
  smooth_page_indicator: ^0.1.3
  auto_size_text: ^2.1.0
  flutter_email_sender: ^2.2.2
  image_fade: ^0.2.1
  cached_network_image: ^2.0.0
  dropdown_menu: ^1.1.1
  progress_dialog: ^1.2.0
  flutter_staggered_grid_view: ^0.3.0
  youtube_player: ^3.5.0
  # connectivity: 
  # contacts_service:
  # simple_permissions:
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lang/en-US.json
    - assets/lang/ar-SA.json
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Black.ttf
          weight: 900
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
